### ISSUE TITLE
ngx-translate.com domain expired?

### ISSUE THREAD

**Issue by localpcguy** [ngx-translate/ngx-translate-website#8]
Just a heads up @ocombe that it looks like the `ngx-translate.com` domain expired recently and appears to have been picked up by an auction site? Not going to post the link directly, but the domain itself is redirecting to the auction as of 3/20/24.

**Comment by ocombe** [comment]
Yeah I know, I removed the link from the organization. I didn't make sense to pay for the domain as it's not really useful. But thanks for the heads up.
